# Dev Environment Overrides

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.mlvbxtjjwahtcdbtdpgd
spring.datasource.password=XK3JTfSc1tBObl3V

# HikariCP (Prevent closed connection errors from Supabase PgBouncer)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.connection-test-query=SELECT 1



# Auto-update database schema and show SQL in dev
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dev Email Config
spring.mail.username=evaira.shopping@gmail.com
spring.mail.password=fzkyakyvkwjurgml

# Dev JWT Token
jwt.secret=change_this_super_secret_key_123
jwt.expiration-ms=864000000

# Enable Swagger in Dev
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Supabase Auth configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://mlvbxtjjwahtcdbtdpgd.supabase.co/auth/v1

# # Spring Security Debug Logs (Shows exact reason for 401 errors)
# logging.level.org.springframework.security=INFO
# logging.level.org.springframework.security.oauth2=INFO


