#spring.application.name=evaira-backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/evairadb
#spring.datasource.username=myuser
#spring.datasource.password=password


spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres.nehnchvvolredwwgvmah}
spring.datasource.password=${DB_PASSWORD:Evaira@12#Shopping}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.generate-ddl=${JPA_GENERATE_DDL:false}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

# Email Configs
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:evaira.shopping@gmail.com}
spring.mail.password=${MAIL_PASSWORD:fzkyakyvkwjurgml}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#JWT Token
jwt.secret=${JWT_SECRET:change_this_super_secret_key_123}
jwt.expiration-ms=${JWT_EXPIRATION_MS:864000000}

server.address=0.0.0.0
server.port=8080

# Swagger/OpenAPI Config
springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}
