spring.application.name=evaira-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/evairadb
spring.datasource.username=myuser
spring.datasource.password=password

#spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/evairadb
#spring.datasource.username=postgres.ofdlddmklniziqdoxzhf
#spring.datasource.password=EfiMSkp0TI9hHC3r
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# Email Configs
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=evaira.shopping@gmail.com
spring.mail.password=fzkyakyvkwjurgml
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#JWT Token
jwt.secret=change_this_super_secret_key_123
jwt.expiration-ms=86400000

server.address=0.0.0.0
logging.level.org.springframework.security=DEBUG
server.port=8082

